### ISSUE TITLE
[EnvyHunt] Unable to use Custom NBT Tags

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [EnvyWare/EnvyHunt#28]
I've been trying to make a pixelmon:pixelmon_sprite to look like a Ditto in the reward's GUI by writing the NBT Tags like below, but when changed this only prevents the hunt's GUI to load. Also tried it for keys in Nebula, none work and the same issue happens.
```

nbt:
        form:
            type: string
            data: ''
            sub-data: {}
        gender:
            type: byte
            data: '2'
            sub-data: {}
        ndex:
            type: short
            data: '132'
            sub-data: {}
        palette:
            type: string
            data: 'none'
            sub-data: {}

```
